# O nome do seu projeto no Cloudflare Pages.
name = "pave-react"

# O diretório onde o Vite coloca os arquivos finais do build do frontend.
pages_build_output_dir = "dist"

# Define a compatibilidade do ambiente de execução do Worker.
compatibility_date = "2025-09-24"

# --- Variáveis de Ambiente para Desenvolvimento Local ---
[vars]
GEMINI_API_KEY = "AIzaSyAp4KK4sR4vLm1n9y-iHyt1KX0tq5Yv2ik"
CF_ENV = "development"
INDEXING_SECRET = "XSAASX"
PAVE_UPLOADER_BASE_URL = "https://pave-uploader.pedroalexis016.workers.dev"
PAVE_UPLOADER_ADMIN_USER = "admin"
PAVE_UPLOADER_ADMIN_PASSWORD = "admin123"

# --- Bindings de Recursos da Cloudflare ---

# Binding para o R2 Bucket
[[r2_buckets]]
binding = "QUESTOES_PAVE_BUCKET"
bucket_name = "chatbot-pave-questoes-2024"

# Binding para o Vectorize Index
[[vectorize]]
binding = "QUESTIONS_INDEX"
index_name = "questions-index"

# Binding para Workers AI
[ai]
binding = "AI"
